import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { QueryClient, QueryClientProvider } from 'react-query';
import { useState } from 'react';
import { TopicForm } from './components/TopicForm';
import { QuizPlayer } from './components/QuizPlayer';
import { ResultsView } from './components/ResultsView';
import { HistoryPage } from './pages/HistoryPage';
import { useQuiz } from './hooks/useQuiz';
const queryClient = new QueryClient();
function QuizApp() {
    const [tab, setTab] = useState('quiz');
    const { phase, quiz, result, answers, error, allAnswered, generate, selectAnswer, submit, reset } = useQuiz();
    return (_jsx("div", { className: "min-h-screen bg-[radial-gradient(circle_at_top_left,_#dbeafe_0,_transparent_32%),linear-gradient(135deg,_#f8fafc_0%,_#eef2ff_48%,_#f9fafb_100%)] px-4 py-6 text-slate-900 sm:px-6 lg:px-8", children: _jsx("div", { className: "mx-auto flex min-h-[calc(100vh-3rem)] w-full max-w-5xl items-center", children: _jsxs("main", { className: "grid w-full overflow-hidden rounded-[2rem] border border-white/70 bg-white/80 shadow-soft backdrop-blur xl:grid-cols-[0.9fr_1.1fr]", children: [_jsxs("aside", { className: "hidden border-r border-slate-200/80 bg-slate-950 p-10 text-white xl:flex xl:flex-col xl:justify-between", children: [_jsxs("div", { children: [_jsx("div", { className: "mb-10 inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan-400 text-xl font-black text-slate-950", children: "AI" }), _jsx("p", { className: "text-sm font-semibold uppercase tracking-[0.22em] text-cyan-200", children: "Smart learning studio" }), _jsx("h1", { className: "mt-4 text-4xl font-bold leading-tight tracking-tight", children: "Build focused quizzes in seconds." }), _jsx("p", { className: "mt-5 max-w-sm text-sm leading-6 text-slate-300", children: "Practice any topic with adaptive difficulty, instant scoring, and clean feedback for every answer." })] }), _jsx("div", { className: "grid grid-cols-3 gap-3 text-center", children: ['Topic', 'Quiz', 'Review'].map(item => (_jsx("div", { className: "rounded-2xl border border-white/10 bg-white/5 px-3 py-4", children: _jsx("div", { className: "text-xs font-medium text-slate-300", children: item }) }, item))) })] }), _jsxs("section", { className: "w-full px-5 py-6 sm:px-8 sm:py-8 lg:px-12", children: [_jsx("div", { className: "mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between", children: _jsxs("div", { children: [_jsx("p", { className: "mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-cyan-700", children: "AI Quiz Builder" }), _jsx("h1", { className: "text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl", children: "Practice with precision" }), _jsx("p", { className: "mt-2 max-w-xl text-sm leading-6 text-slate-500", children: "Enter any topic and get a personalized quiz powered by AI." })] }) }), _jsx("div", { className: "mb-7 inline-flex rounded-full border border-slate-200 bg-slate-100 p-1 shadow-sm", children: ['quiz', 'history'].map(t => (_jsx("button", { onClick: () => setTab(t), className: `rounded-full px-5 py-2 text-sm font-semibold capitalize transition-all ${tab === t
                                        ? 'bg-white text-slate-950 shadow-sm'
                                        : 'text-slate-500 hover:text-slate-800'}`, children: t }, t))) }), _jsx("div", { className: "min-h-[430px]", children: tab === 'history' ? (_jsx(HistoryPage, {})) : (_jsxs(_Fragment, { children: [(phase === 'idle' || phase === 'loading' || phase === 'error') && (_jsxs(_Fragment, { children: [_jsx(TopicForm, { onSubmit: generate, loading: phase === 'loading' }), error && (_jsx("p", { className: "mt-4 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-medium text-red-700", children: error }))] })), (phase === 'playing' || phase === 'submitting') && quiz && (_jsx(QuizPlayer, { questions: quiz.questions, answers: answers, onSelect: selectAnswer, onSubmit: submit, allAnswered: allAnswered, submitting: phase === 'submitting' })), phase === 'results' && result && (_jsx(ResultsView, { result: result, onRetry: reset }))] })) })] })] }) }) }));
}
export default function App() {
    return (_jsx(QueryClientProvider, { client: queryClient, children: _jsx(QuizApp, {}) }));
}
